public class collections {
    public static string ListAssignment (Integer n){
         List<String> ListMonth = new List <String>();
        string outputMonth = ' ';

        ListMonth.add('');
        ListMonth.add('January');
        ListMonth.add('February');
        ListMonth.add('March');
        ListMonth.add('April');
        ListMonth.add('May');
        ListMonth.add('June');
        ListMonth.add('July');
        ListMonth.add('August');
        ListMonth.add('September');
        ListMonth.add('October');
        ListMonth.add('November');
        ListMonth.add('December');
        system.debug(ListMonth);





    }
}