public class ListExtra_Assignment {
    public static void schoolsList(string medium){
        List<String> mediumSchoolList = new List<String>();
        List<String> citiessl = new List<String>{
            'S1 English', 'S2 English', 'S3 Turkish', 'S4 English','S5 Turkish', 'S6 Japanese'
        };
        for (string eachSchool : citiessl) {
            system.debug(eachSchool);
            
        }

    }



}