public class LoopDemoBurak {
    public void print_int_while(){
        integer count = 1;
        while (count <= 25) {
            system.debug (count);
            count++;
        }
    }
        for(integer i=0; i<5; i++){
        system.debug(i);
    }

    // string olarak girilen istanbul telefon numarasinin avrupa mi anadolu yakasina mi ait oldugunu donduren bir method yazin
    public void phone(string phoneNumber){
        //once parametrenin(numaranin) 10 haneli olup olmadigini kontrol edelim.
        //gelen telefon numarasinin ilk3 hanesini alip kontrol edelim 212, 216
        //3 tane condition olmali; anadolu, avrupa, ya da baska bir telefon numarasi.
        //
    }
}